/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package n1exercici1;

public class App {
    
	public static void main(String[] args) {
		
		AgentBorsa pepe = new AgentBorsa("Pepe");
		
		pepe.afegirAgencia(new AgenciaBorsa("Mentalidad Tiburon"));
		pepe.afegirAgencia(new AgenciaBorsa("Se tu propio jefe"));
		pepe.afegirAgencia(new AgenciaBorsa("Volem Diners"));
		
		
		pepe.notificarBaixada();
		pepe.notificarPujada();
	}
}
