/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package n1exercici1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
	
}
